version: "3"

networks:
  dashboard_nextjs:
    driver: bridge

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: dashboard-main
    stdin_open: true
    volumes:
      - ./:/app
    networks:
      - dashboard_nextjs  # Updated network name


  backend:
    build:
      context: .
      dockerfile: ./backened/Dockerfile
    ports:
      - 5000:5000
    container_name: backend-server